package pacman.controllers.Assignment3.Tree;

public enum Attribute {
    DirectionChosen,
    mazeIndex,
    currentLevel,
    pacmanPosition,
    pacmanLivesLeft,
    currentScore,
    totalGameTime,
    currentLevelTime,
    numOfPillsLeft,
    numPowerPillsLeft,
    isBlinkyEdible,
    isInkyEdible,
    isPinkyEdible,
    isSueEdible,
    blinkyDist,
    inkyDist,
    pinkyDist,
    sueDist,
    blinkyDir,
    inkyDir,
    pinkyDir,
    sueDir,
    numberOfNodesInLevel,
    numberOfTotalPillsInLevel,
    numberOfTotalPowerPillsInLevel,
    maximumDistance
}
